### ISSUE TITLE
EDIT: Remove this, I'm dumb.

### ISSUE THREAD

**Issue by ragsmaroon** [yukisuki/startpage#2]
EDIT: I'm a fucking idiot. Wish this had Chrome support though :/

**Comment by yukisuki** [comment]
I think this is related to [chromium's issue 40787](https://code.google.com/p/chromium/issues/detail?id=40787).
You'll have to start Chrome/Chromium with _--allow-file-access-from-files_, otherwise it won't be able to load _config.json_. You will also have to add `var cfg = 0, cfg_bool = 0;` before `$.getJSON("config.json", function(data){` in _main.js_, because chrome doesn't make those variables automatically global for some reason.

**Comment by ragsmaroon** [comment]
That worked! Thank you very much.
